version: '3'
services:
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    security_opt:
      - seccomp:unconfined
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '12345:8000'
    volumes:
      - ./tabelogger:/work/tabelogger
